# This is a basic workflow to help you get started with Actions

name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Mendownload Ngrok.
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1-UE40Y76UfV4bXbRs85kIm_IRKXeI-bT -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/khafidzu/Anak/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1j8gpfAxWYgF3ufu582QeqhhWfPwNeOmD -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/khafidzu/Anak/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/khafidzu/Anak/main/loop.bat -OutFile loop.bat
    - name: Mendownload Launcher.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/khafidzu/Anak/main/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/khafidzu/Anak/main/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Mengextract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect Ke Akun Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Mengaktifkan Akses RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: Membuat Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: Berhasil Dibuat! Anda Bisa Menutup Tab Sekarang.
      run: cmd /c loop.bat
